channels:
  - defaults
  - conda-forge
  - fastai
dependencies:
  - python=3.8
  - jupyter
  - jupyterlab
  - notebook
  - jupyter_contrib_nbextensions
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - pytorch
  - pydantic=1.8.2
  - sentencepiece
  - fastai
  - fastbook
  - openpyxl
  - dtreeviz=1.4.1
